[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "d5p1"
path = "src/d5p1.rs"

[[bin]]
name = "d5p2"
path = "src/d5p2.rs"

[[bin]]
name = "d6p1"
path = "src/d6p1.rs"

[[bin]]
name = "d6p2"
path = "src/d6p2.rs"
